/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-tint": "#a73a00",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#586377",
        "surface": "#f9f9f9",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-fixed": "#111c2d",
        "on-primary-fixed-variant": "#7f2b00",
        "tertiary-container": "#6c748b",
        "surface-container": "#eeeeee",
        "outline": "#8e7166",
        "primary-fixed-dim": "#ffb599",
        "on-surface-variant": "#5a4138",
        "primary-fixed": "#ffdbce",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#3f465c",
        "tertiary": "#545c72",
        "on-background": "#1a1c1c",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#dae2fd",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-fixed-dim": "#bcc7de",
        "secondary-container": "#d5e0f8",
        "primary-container": "#cc4900",
        "on-primary-fixed": "#370e00",
        "inverse-primary": "#ffb599",
        "outline-variant": "#e2bfb2",
        "surface-variant": "#e2e2e2",
        "on-primary-container": "#fffbff",
        "surface-container-highest": "#e2e2e2",
        "secondary": "#545f73",
        "surface-dim": "#dadada",
        "surface-container-high": "#e8e8e8",
        "background": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#131b2e",
        "on-tertiary-container": "#fefcff",
        "primary": "#a33900",
        "surface-container-low": "#f3f3f4"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
    },
  },
  plugins: [],
}
